### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by ChrisdeG** [bit3/jsass-docs#2]
I get no exceptions on error. Is that an option. Result is now simply 'null'

**Comment by tristanlins** [comment]
This repository is only the documentation, please fill an issue in the [jsass repository](https://github.com/bit3/jsass/issues).

But to answer your question. jsass will not throw exceptions. But the output has an error status. see https://github.com/bit3/jsass/blob/master/src/main/java/io/bit3/jsass/Output.java#L18-L31
